from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1820, 980)
        MainWindow.setMinimumSize(QtCore.QSize(1820, 980))
        MainWindow.setMaximumSize(QtCore.QSize(1820, 980))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(30, 10, 1761, 61))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_set100 = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushButton_set100.setMinimumSize(QtCore.QSize(150, 50))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.pushButton_set100.setFont(font)
        self.pushButton_set100.setObjectName("pushButton_set100")
        self.horizontalLayout.addWidget(self.pushButton_set100)
        self.pushButton_nasdaq = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushButton_nasdaq.setMinimumSize(QtCore.QSize(150, 50))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.pushButton_nasdaq.setFont(font)
        self.pushButton_nasdaq.setObjectName("pushButton_nasdaq")
        self.horizontalLayout.addWidget(self.pushButton_nasdaq)
        self.pushButton_crypto = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushButton_crypto.setMinimumSize(QtCore.QSize(150, 50))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.pushButton_crypto.setFont(font)
        self.pushButton_crypto.setObjectName("pushButton_crypto")
        self.horizontalLayout.addWidget(self.pushButton_crypto)
        self.comboBox_set100 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_set100.setGeometry(QtCore.QRect(30, 90, 1531, 41))
        self.comboBox_set100.setObjectName("comboBox_set100")
        self.pushButton_loadset100 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_loadset100.setGeometry(QtCore.QRect(1590, 90, 201, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.pushButton_loadset100.setFont(font)
        self.pushButton_loadset100.setObjectName("pushButton_loadset100")
        self.pushButton_dataset100 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_dataset100.setGeometry(QtCore.QRect(140, 160, 81, 31))
        self.pushButton_dataset100.setObjectName("pushButton_dataset100")
        self.pushButton_infoset100 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_infoset100.setGeometry(QtCore.QRect(240, 160, 81, 31))
        self.pushButton_infoset100.setObjectName("pushButton_infoset100")
        self.tableWidget_set100 = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget_set100.setGeometry(QtCore.QRect(30, 220, 421, 711))
        self.tableWidget_set100.setObjectName("tableWidget_set100")
        self.tableWidget_set100.setColumnCount(7)
        self.tableWidget_set100.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_set100.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_set100.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_set100.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_set100.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_set100.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_set100.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_set100.setHorizontalHeaderItem(6, item)
        self.tableWidget_infoset100 = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget_infoset100.setGeometry(QtCore.QRect(30, 220, 421, 271))
        self.tableWidget_infoset100.setObjectName("tableWidget_infoset100")
        self.tableWidget_infoset100.setColumnCount(1)
        self.tableWidget_infoset100.setRowCount(8)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_infoset100.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_infoset100.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_infoset100.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_infoset100.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_infoset100.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_infoset100.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_infoset100.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_infoset100.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_infoset100.setHorizontalHeaderItem(0, item)
        self.tableWidget_nasdaq = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget_nasdaq.setGeometry(QtCore.QRect(30, 220, 421, 711))
        self.tableWidget_nasdaq.setObjectName("tableWidget_nasdaq")
        self.tableWidget_nasdaq.setColumnCount(7)
        self.tableWidget_nasdaq.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_nasdaq.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_nasdaq.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_nasdaq.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_nasdaq.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_nasdaq.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_nasdaq.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_nasdaq.setHorizontalHeaderItem(6, item)
        self.tableWidget_crypto = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget_crypto.setGeometry(QtCore.QRect(30, 220, 421, 711))
        self.tableWidget_crypto.setObjectName("tableWidget_crypto")
        self.tableWidget_crypto.setColumnCount(7)
        self.tableWidget_crypto.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_crypto.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_crypto.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_crypto.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_crypto.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_crypto.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_crypto.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_crypto.setHorizontalHeaderItem(6, item)
        self.tableWidget_infonasdaq = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget_infonasdaq.setGeometry(QtCore.QRect(30, 220, 421, 271))
        self.tableWidget_infonasdaq.setObjectName("tableWidget_infonasdaq")
        self.tableWidget_infonasdaq.setColumnCount(1)
        self.tableWidget_infonasdaq.setRowCount(8)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_infonasdaq.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_infonasdaq.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_infonasdaq.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_infonasdaq.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_infonasdaq.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_infonasdaq.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_infonasdaq.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_infonasdaq.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_infonasdaq.setHorizontalHeaderItem(0, item)
        self.pushButton_datanasdaq = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_datanasdaq.setGeometry(QtCore.QRect(140, 160, 81, 31))
        self.pushButton_datanasdaq.setObjectName("pushButton_datanasdaq")
        self.pushButton_datacrypto = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_datacrypto.setGeometry(QtCore.QRect(140, 160, 81, 31))
        self.pushButton_datacrypto.setObjectName("pushButton_datacrypto")
        self.pushButton_infonasdaq = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_infonasdaq.setGeometry(QtCore.QRect(240, 160, 81, 31))
        self.pushButton_infonasdaq.setObjectName("pushButton_infonasdaq")
        self.comboBox_nasdaq = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_nasdaq.setGeometry(QtCore.QRect(30, 90, 1531, 41))
        self.comboBox_nasdaq.setObjectName("comboBox_nasdaq")
        self.comboBox_crypto = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_crypto.setGeometry(QtCore.QRect(30, 90, 1531, 41))
        self.comboBox_crypto.setObjectName("comboBox_crypto")
        self.pushButton_loadnasdaq = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_loadnasdaq.setGeometry(QtCore.QRect(1590, 90, 201, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.pushButton_loadnasdaq.setFont(font)
        self.pushButton_loadnasdaq.setObjectName("pushButton_loadnasdaq")
        self.pushButton_loadcrypto = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_loadcrypto.setGeometry(QtCore.QRect(1590, 90, 201, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.pushButton_loadcrypto.setFont(font)
        self.pushButton_loadcrypto.setObjectName("pushButton_loadcrypto")
        self.pushButton_loadcrypto.raise_()
        self.pushButton_loadnasdaq.raise_()
        self.comboBox_crypto.raise_()
        self.comboBox_nasdaq.raise_()
        self.tableWidget_crypto.raise_()
        self.tableWidget_nasdaq.raise_()
        self.pushButton_datacrypto.raise_()
        self.pushButton_datanasdaq.raise_()
        self.pushButton_infonasdaq.raise_()
        self.tableWidget_infonasdaq.raise_()
        self.tableWidget_infoset100.raise_()
        self.tableWidget_set100.raise_()
        self.horizontalLayoutWidget.raise_()
        self.comboBox_set100.raise_()
        self.pushButton_loadset100.raise_()
        self.pushButton_dataset100.raise_()
        self.pushButton_infoset100.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1820, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.pushButton_dataset100.clicked.connect(self.tableWidget_set100.show) # type: ignore
        self.pushButton_dataset100.clicked.connect(self.tableWidget_infoset100.hide) # type: ignore
        self.pushButton_infoset100.clicked.connect(self.tableWidget_set100.hide) # type: ignore
        self.pushButton_infoset100.clicked.connect(self.tableWidget_infoset100.show) # type: ignore
        self.pushButton_set100.clicked.connect(self.comboBox_set100.show) # type: ignore
        self.pushButton_set100.clicked.connect(self.pushButton_loadset100.show) # type: ignore
        self.pushButton_set100.clicked.connect(self.tableWidget_nasdaq.hide) # type: ignore
        self.pushButton_set100.clicked.connect(self.tableWidget_crypto.hide) # type: ignore
        self.pushButton_set100.clicked.connect(self.tableWidget_infonasdaq.hide) # type: ignore
        self.pushButton_set100.clicked.connect(self.pushButton_infonasdaq.hide) # type: ignore
        self.pushButton_set100.clicked.connect(self.pushButton_datanasdaq.hide) # type: ignore
        self.pushButton_set100.clicked.connect(self.pushButton_datacrypto.hide) # type: ignore
        self.pushButton_nasdaq.clicked.connect(self.pushButton_infonasdaq.show) # type: ignore
        self.pushButton_nasdaq.clicked.connect(self.tableWidget_nasdaq.show) # type: ignore
        self.pushButton_nasdaq.clicked.connect(self.pushButton_datanasdaq.show) # type: ignore
        self.pushButton_infonasdaq.clicked.connect(self.tableWidget_infonasdaq.show) # type: ignore
        self.pushButton_infonasdaq.clicked.connect(self.tableWidget_nasdaq.hide) # type: ignore
        self.pushButton_datanasdaq.clicked.connect(self.tableWidget_nasdaq.show) # type: ignore
        self.pushButton_datanasdaq.clicked.connect(self.tableWidget_infonasdaq.hide) # type: ignore
        self.pushButton_nasdaq.clicked.connect(self.tableWidget_crypto.hide) # type: ignore
        self.pushButton_nasdaq.clicked.connect(self.comboBox_set100.hide) # type: ignore
        self.pushButton_nasdaq.clicked.connect(self.pushButton_loadset100.hide) # type: ignore
        self.pushButton_crypto.clicked.connect(self.comboBox_set100.hide) # type: ignore
        self.pushButton_crypto.clicked.connect(self.pushButton_loadset100.hide) # type: ignore
        self.pushButton_set100.clicked.connect(self.comboBox_nasdaq.hide) # type: ignore
        self.pushButton_set100.clicked.connect(self.comboBox_crypto.hide) # type: ignore
        self.pushButton_set100.clicked.connect(self.pushButton_loadnasdaq.hide) # type: ignore
        self.pushButton_set100.clicked.connect(self.pushButton_loadcrypto.hide) # type: ignore
        self.pushButton_nasdaq.clicked.connect(self.comboBox_nasdaq.show) # type: ignore
        self.pushButton_nasdaq.clicked.connect(self.pushButton_loadnasdaq.show) # type: ignore
        self.pushButton_nasdaq.clicked.connect(self.comboBox_crypto.hide) # type: ignore
        self.pushButton_nasdaq.clicked.connect(self.pushButton_loadcrypto.hide) # type: ignore
        self.pushButton_crypto.clicked.connect(self.comboBox_nasdaq.hide) # type: ignore
        self.pushButton_crypto.clicked.connect(self.pushButton_loadnasdaq.hide) # type: ignore
        self.pushButton_crypto.clicked.connect(self.comboBox_crypto.show) # type: ignore
        self.pushButton_crypto.clicked.connect(self.pushButton_loadcrypto.show) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_set100.setText(_translate("MainWindow", "SET100"))
        self.pushButton_nasdaq.setText(_translate("MainWindow", "NASDAQ"))
        self.pushButton_crypto.setText(_translate("MainWindow", "CRYPTO"))
        self.pushButton_loadset100.setText(_translate("MainWindow", "Update"))
        self.pushButton_dataset100.setText(_translate("MainWindow", "Data"))
        self.pushButton_infoset100.setText(_translate("MainWindow", "Information"))
        item = self.tableWidget_set100.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Date"))
        item = self.tableWidget_set100.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Open"))
        item = self.tableWidget_set100.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "High"))
        item = self.tableWidget_set100.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Low"))
        item = self.tableWidget_set100.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Close"))
        item = self.tableWidget_set100.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Volume"))
        item = self.tableWidget_set100.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Symbol"))
        item = self.tableWidget_infoset100.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "Symbol"))
        item = self.tableWidget_infoset100.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "Market"))
        item = self.tableWidget_infoset100.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "Industry Symbol"))
        item = self.tableWidget_infoset100.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "Industry"))
        item = self.tableWidget_infoset100.verticalHeaderItem(4)
        item.setText(_translate("MainWindow", "Sector Symbol"))
        item = self.tableWidget_infoset100.verticalHeaderItem(5)
        item.setText(_translate("MainWindow", "Sector"))
        item = self.tableWidget_infoset100.verticalHeaderItem(6)
        item.setText(_translate("MainWindow", "Dividend Policy"))
        item = self.tableWidget_infoset100.verticalHeaderItem(7)
        item.setText(_translate("MainWindow", "Business Type"))
        item = self.tableWidget_infoset100.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Information"))
        item = self.tableWidget_nasdaq.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Date"))
        item = self.tableWidget_nasdaq.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Open"))
        item = self.tableWidget_nasdaq.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "High"))
        item = self.tableWidget_nasdaq.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Low"))
        item = self.tableWidget_nasdaq.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Close"))
        item = self.tableWidget_nasdaq.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Volume"))
        item = self.tableWidget_nasdaq.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Symbol"))
        item = self.tableWidget_crypto.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Date"))
        item = self.tableWidget_crypto.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Open"))
        item = self.tableWidget_crypto.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "High"))
        item = self.tableWidget_crypto.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Low"))
        item = self.tableWidget_crypto.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Close"))
        item = self.tableWidget_crypto.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Volume"))
        item = self.tableWidget_crypto.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Symbol"))
        item = self.tableWidget_infonasdaq.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "Symbol"))
        item = self.tableWidget_infonasdaq.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "Market"))
        item = self.tableWidget_infonasdaq.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "Industry Symbol"))
        item = self.tableWidget_infonasdaq.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "Industry"))
        item = self.tableWidget_infonasdaq.verticalHeaderItem(4)
        item.setText(_translate("MainWindow", "Sector Symbol"))
        item = self.tableWidget_infonasdaq.verticalHeaderItem(5)
        item.setText(_translate("MainWindow", "Sector"))
        item = self.tableWidget_infonasdaq.verticalHeaderItem(6)
        item.setText(_translate("MainWindow", "Dividend Policy"))
        item = self.tableWidget_infonasdaq.verticalHeaderItem(7)
        item.setText(_translate("MainWindow", "Business Type"))
        item = self.tableWidget_infonasdaq.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Information"))
        self.pushButton_datanasdaq.setText(_translate("MainWindow", "Data"))
        self.pushButton_datacrypto.setText(_translate("MainWindow", "Data"))
        self.pushButton_infonasdaq.setText(_translate("MainWindow", "Information"))
        self.pushButton_loadnasdaq.setText(_translate("MainWindow", "Update"))
        self.pushButton_loadcrypto.setText(_translate("MainWindow", "Update"))
