from PyQt5 import QtCore, QtGui, QtWidgets, QtWebEngineWidgets
import sqlite3

class Ui_MainWindow(object):
#---------------------------------------------------------------- Load Data All
#     def load_data_set(self):
#         conn = sqlite3.connect('share_V3.sqlite')
#         cur = conn.cursor()
#         sqlquery = f"""SELECT SP."Date",SP.Open,Sp.High,SP.Low,SP.Close,SP.Volume,I.Symbol FROM Stock_price_day as SP 
#                         INNER JOIN Information as I on I.SymbolId = SP.SymbolId;"""
#         result = conn.execute(sqlquery)
#         self.tableWidget_dataset.setRowCount(0)
#         for row_num, row_data in enumerate(result):
#             self.tableWidget_dataset.insertRow(row_num)
#             for column_num, data in enumerate(row_data):
#                 self.tableWidget_dataset.setItem(row_num, column_num, QtWidgets.QTableWidgetItem(str(data)))

    def load_fncset_all(self):
        pass
    
    def load_fncnasdaq_all(self):
        pass

    def load_dataset(self):
        selected_item = self.comboBox_dataset.currentText()
        conn = sqlite3.connect('share_V3.sqlite')
        cursor = conn.cursor()
        sqlquery = f"""SELECT i.Symbol,i.Sname,m.Mname,s.Full_sector,i.Description FROM Information as i
                        INNER JOIN Market as m ON m.MarketId = i.MarketId
                        INNER JOIN Sector as s ON s.MarketId = i.MarketId
                        WHERE Symbol = '{str(selected_item)}';"""
        result = conn.execute(sqlquery)
        self.tableWidget_searchset.setRowCount(0)
        for row_num, row_data in enumerate(result):
            self.tableWidget_searchset.insertRow(row_num)
            for column_num, data in enumerate(row_data):
                self.tableWidget_searchset.setItem(row_num, column_num, QtWidgets.QTableWidgetItem(str(data)))
        conn.close()

    def load_datanasdaq(self):
        pass
    
    def load_datacrypto(self):
        pass
    
    def load_fncset(self):
        pass
    
    def load_fncnasdaq(self):
        pass
    
    def load_newsset(self):
        pass
    
    def load_newsnasdaq(self):
        pass
    
    def load_newscrypto(self):
        pass
    
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1820, 920)
        MainWindow.setMinimumSize(QtCore.QSize(1820, 920))
        MainWindow.setMaximumSize(QtCore.QSize(1820, 920))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.All = QtWidgets.QWidget(self.centralwidget)
        self.All.setGeometry(QtCore.QRect(0, 0, 1821, 951))
        self.All.setStyleSheet("background-color: #353535;")
        self.All.setObjectName("All")
        self.Header = QtWidgets.QFrame(self.All)
        self.Header.setGeometry(QtCore.QRect(0, 0, 1821, 71))
        self.Header.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Header.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Header.setObjectName("Header")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.Header)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_data = QtWidgets.QPushButton(self.Header)
        self.pushButton_data.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButton_data.setFont(font)
        self.pushButton_data.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_data.setStyleSheet("background-color: #E9EBEF;")
        self.pushButton_data.setObjectName("pushButton_data")
        self.horizontalLayout.addWidget(self.pushButton_data)
        self.pushButton_graph = QtWidgets.QPushButton(self.Header)
        self.pushButton_graph.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButton_graph.setFont(font)
        self.pushButton_graph.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_graph.setStyleSheet("background-color: #E9EBEF;")
        self.pushButton_graph.setObjectName("pushButton_graph")
        self.horizontalLayout.addWidget(self.pushButton_graph)
        self.pushButton_financial = QtWidgets.QPushButton(self.Header)
        self.pushButton_financial.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButton_financial.setFont(font)
        self.pushButton_financial.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_financial.setStyleSheet("background-color: #E9EBEF;")
        self.pushButton_financial.setObjectName("pushButton_financial")
        self.horizontalLayout.addWidget(self.pushButton_financial)
        self.pushButton_news = QtWidgets.QPushButton(self.Header)
        self.pushButton_news.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButton_news.setFont(font)
        self.pushButton_news.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_news.setStyleSheet("background-color: #E9EBEF;")
        self.pushButton_news.setObjectName("pushButton_news")
        self.horizontalLayout.addWidget(self.pushButton_news)
        self.DataPage = QtWidgets.QWidget(self.All)
        self.DataPage.setGeometry(QtCore.QRect(30, 80, 1761, 791))
        self.DataPage.setStyleSheet("background-color: #353535;")
        self.DataPage.setObjectName("DataPage")
        self.Data_select = QtWidgets.QWidget(self.DataPage)
        self.Data_select.setGeometry(QtCore.QRect(0, 0, 321, 791))
        self.Data_select.setStyleSheet("background-color: #E9EBEF;")
        self.Data_select.setObjectName("Data_select")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.Data_select)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 20, 301, 180))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.pushButton_dataset = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton_dataset.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pushButton_dataset.setFont(font)
        self.pushButton_dataset.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_dataset.setStyleSheet("background-color: #D2D7DF;")
        self.pushButton_dataset.setObjectName("pushButton_dataset")
        self.verticalLayout.addWidget(self.pushButton_dataset)
        self.pushButton_datanasdaq = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton_datanasdaq.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pushButton_datanasdaq.setFont(font)
        self.pushButton_datanasdaq.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_datanasdaq.setStyleSheet("background-color: #D2D7DF;")
        self.pushButton_datanasdaq.setObjectName("pushButton_datanasdaq")
        self.verticalLayout.addWidget(self.pushButton_datanasdaq)
        self.pushButton_datacrypto = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton_datacrypto.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pushButton_datacrypto.setFont(font)
        self.pushButton_datacrypto.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_datacrypto.setStyleSheet("background-color: #D2D7DF;")
        self.pushButton_datacrypto.setObjectName("pushButton_datacrypto")
        self.verticalLayout.addWidget(self.pushButton_datacrypto)
        self.tablenasdaq = QtWidgets.QWidget(self.DataPage)
        self.tablenasdaq.setGeometry(QtCore.QRect(350, 0, 1411, 791))
        self.tablenasdaq.setStyleSheet("background-color: #D2D7DF;")
        self.tablenasdaq.setObjectName("tablenasdaq")
        self.tableWidget_datanasdaq = QtWidgets.QTableWidget(self.tablenasdaq)
        self.tableWidget_datanasdaq.setGeometry(QtCore.QRect(0, 0, 1411, 600))
        self.tableWidget_datanasdaq.setMaximumSize(QtCore.QSize(1411, 16777215))
        self.tableWidget_datanasdaq.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.tableWidget_datanasdaq.setObjectName("tableWidget_datanasdaq")
        self.tableWidget_datanasdaq.setColumnCount(4)
        self.tableWidget_datanasdaq.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_datanasdaq.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_datanasdaq.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_datanasdaq.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_datanasdaq.setHorizontalHeaderItem(3, item)
        self.tableWidget_datanasdaq.horizontalHeader().setDefaultSectionSize(350)
        self.comboBox_datanasdaq = QtWidgets.QComboBox(self.tablenasdaq)
        self.comboBox_datanasdaq.setGeometry(QtCore.QRect(0, 620, 1241, 31))
        self.comboBox_datanasdaq.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.comboBox_datanasdaq.setStyleSheet("background-color:#ffffff;")
        self.comboBox_datanasdaq.setObjectName("comboBox_datanasdaq")
#----------------------------------------------------------------- Combobox Search Data Nasdaq
        self.comboBox_datanasdaq.setEditable(True)
        self.comboBox_datanasdaq.setInsertPolicy(QtWidgets.QComboBox.NoInsert)
        self.comboBox_datanasdaq.completer().setCompletionMode(QtWidgets.QCompleter.PopupCompletion)

        self.tableWidget_searchnasdaq = QtWidgets.QTableWidget(self.tablenasdaq)
        self.tableWidget_searchnasdaq.setGeometry(QtCore.QRect(0, 670, 1411, 121))
        self.tableWidget_searchnasdaq.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.tableWidget_searchnasdaq.setObjectName("tableWidget_searchnasdaq")
        self.tableWidget_searchnasdaq.setColumnCount(5)
        self.tableWidget_searchnasdaq.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_searchnasdaq.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_searchnasdaq.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_searchnasdaq.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_searchnasdaq.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_searchnasdaq.setHorizontalHeaderItem(4, item)
        self.tableWidget_searchnasdaq.horizontalHeader().setDefaultSectionSize(350)
        self.pushButton_updatenasdaq = QtWidgets.QPushButton(self.tablenasdaq)
        self.pushButton_updatenasdaq.setGeometry(QtCore.QRect(1260, 620, 141, 31))
        self.pushButton_updatenasdaq.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_updatenasdaq.setStyleSheet("background-color: rgb(225, 255, 228);")
        self.pushButton_updatenasdaq.setObjectName("pushButton_updatenasdaq")
        self.tableset = QtWidgets.QWidget(self.DataPage)
        self.tableset.setGeometry(QtCore.QRect(350, 0, 1411, 791))
        self.tableset.setStyleSheet("background-color: #D2D7DF;")
        self.tableset.setObjectName("tableset")
        self.tableWidget_dataset = QtWidgets.QTableWidget(self.tableset)
        self.tableWidget_dataset.setGeometry(QtCore.QRect(0, 0, 1411, 600))
        self.tableWidget_dataset.setMaximumSize(QtCore.QSize(1411, 16777215))
        self.tableWidget_dataset.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.tableWidget_dataset.setObjectName("tableWidget_dataset")
        self.tableWidget_dataset.setColumnCount(5)
        self.tableWidget_dataset.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_dataset.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_dataset.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_dataset.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_dataset.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_dataset.setHorizontalHeaderItem(4, item)
        self.tableWidget_dataset.horizontalHeader().setDefaultSectionSize(150)
#----------------------------------------------------------------- Load Data Set All

        
        self.comboBox_dataset = QtWidgets.QComboBox(self.tableset)
        self.comboBox_dataset.setGeometry(QtCore.QRect(0, 620, 1241, 31))
        self.comboBox_dataset.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.comboBox_dataset.setStyleSheet("background-color:#ffffff;")
        self.comboBox_dataset.setObjectName("comboBox_dataset")
#----------------------------------------------------------------- Combobox Search Data Set
        self.comboBox_dataset.setEditable(True)
        self.comboBox_dataset.setInsertPolicy(QtWidgets.QComboBox.NoInsert)
        self.comboBox_dataset.completer().setCompletionMode(QtWidgets.QCompleter.PopupCompletion)
        self.comboBox_dataset.currentIndexChanged.connect(self.load_dataset)

        self.tableWidget_searchset = QtWidgets.QTableWidget(self.tableset)
        self.tableWidget_searchset.setGeometry(QtCore.QRect(0, 670, 1411, 121))
        self.tableWidget_searchset.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.tableWidget_searchset.setObjectName("tableWidget_searchset")
        self.tableWidget_searchset.setColumnCount(5)
        self.tableWidget_searchset.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_searchset.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_searchset.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_searchset.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_searchset.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_searchset.setHorizontalHeaderItem(4, item)
        self.tableWidget_searchset.horizontalHeader().setDefaultSectionSize(150)
        self.pushButton_updateset = QtWidgets.QPushButton(self.tableset)
        self.pushButton_updateset.setGeometry(QtCore.QRect(1260, 620, 141, 31))
        self.pushButton_updateset.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_updateset.setStyleSheet("background-color: rgb(225, 255, 228);")
        self.pushButton_updateset.setObjectName("pushButton_updateset")
        self.tablecrypto = QtWidgets.QWidget(self.DataPage)
        self.tablecrypto.setGeometry(QtCore.QRect(350, 0, 1411, 791))
        self.tablecrypto.setStyleSheet("background-color: #D2D7DF;")
        self.tablecrypto.setObjectName("tablecrypto")
        self.tableWidget_datacrypto = QtWidgets.QTableWidget(self.tablecrypto)
        self.tableWidget_datacrypto.setGeometry(QtCore.QRect(0, 0, 611, 791))
        self.tableWidget_datacrypto.setMaximumSize(QtCore.QSize(1411, 16777215))
        self.tableWidget_datacrypto.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.tableWidget_datacrypto.setObjectName("tableWidget_datacrypto")
        self.tableWidget_datacrypto.setColumnCount(2)
        self.tableWidget_datacrypto.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_datacrypto.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_datacrypto.setHorizontalHeaderItem(1, item)
        self.tableWidget_datacrypto.horizontalHeader().setDefaultSectionSize(300)
        self.comboBox_datacrypto = QtWidgets.QComboBox(self.tablecrypto)
        self.comboBox_datacrypto.setGeometry(QtCore.QRect(650, 20, 731, 31))
        self.comboBox_datacrypto.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.comboBox_datacrypto.setStyleSheet("background-color:#ffffff;")
        self.comboBox_datacrypto.setObjectName("comboBox_datacrypto")
#----------------------------------------------------------------- Combobox Search Data Crypto
        self.comboBox_datacrypto.setEditable(True)
        self.comboBox_datacrypto.setInsertPolicy(QtWidgets.QComboBox.NoInsert)
        self.comboBox_datacrypto.completer().setCompletionMode(QtWidgets.QCompleter.PopupCompletion)
        
        self.tableWidget_searchcrypto = QtWidgets.QTableWidget(self.tablecrypto)
        self.tableWidget_searchcrypto.setGeometry(QtCore.QRect(700, 80, 611, 71))
        self.tableWidget_searchcrypto.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.tableWidget_searchcrypto.setObjectName("tableWidget_searchcrypto")
        self.tableWidget_searchcrypto.setColumnCount(2)
        self.tableWidget_searchcrypto.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_searchcrypto.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_searchcrypto.setHorizontalHeaderItem(1, item)
        self.tableWidget_searchcrypto.horizontalHeader().setDefaultSectionSize(300)
        self.pushButton_updatecrypto = QtWidgets.QPushButton(self.tablecrypto)
        self.pushButton_updatecrypto.setGeometry(QtCore.QRect(1170, 180, 141, 31))
        self.pushButton_updatecrypto.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_updatecrypto.setStyleSheet("background-color: rgb(225, 255, 228);")
        self.pushButton_updatecrypto.setObjectName("pushButton_updatecrypto")
        self.Data_select.raise_()
        self.tablenasdaq.raise_()
        self.tablecrypto.raise_()
        self.tableset.raise_()
        self.GraphPage = QtWidgets.QWidget(self.All)
        self.GraphPage.setGeometry(QtCore.QRect(30, 80, 1761, 791))
        self.GraphPage.setStyleSheet("background-color: #353535;")
        self.GraphPage.setObjectName("GraphPage")
        self.Graph_select = QtWidgets.QWidget(self.GraphPage)
        self.Graph_select.setGeometry(QtCore.QRect(0, 0, 321, 791))
        self.Graph_select.setStyleSheet("background-color: #E9EBEF;")
        self.Graph_select.setObjectName("Graph_select")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.Graph_select)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(10, 20, 301, 180))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.pushButton_graphset = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.pushButton_graphset.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pushButton_graphset.setFont(font)
        self.pushButton_graphset.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_graphset.setStyleSheet("background-color: #D2D7DF;")
        self.pushButton_graphset.setObjectName("pushButton_graphset")
        self.verticalLayout_2.addWidget(self.pushButton_graphset)
        self.pushButton_graphnasdaq = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.pushButton_graphnasdaq.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pushButton_graphnasdaq.setFont(font)
        self.pushButton_graphnasdaq.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_graphnasdaq.setStyleSheet("background-color: #D2D7DF;")
        self.pushButton_graphnasdaq.setObjectName("pushButton_graphnasdaq")
        self.verticalLayout_2.addWidget(self.pushButton_graphnasdaq)
        self.pushButton_graphcrypto = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.pushButton_graphcrypto.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pushButton_graphcrypto.setFont(font)
        self.pushButton_graphcrypto.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_graphcrypto.setStyleSheet("background-color: #D2D7DF;")
        self.pushButton_graphcrypto.setObjectName("pushButton_graphcrypto")
        self.verticalLayout_2.addWidget(self.pushButton_graphcrypto)
        self.Webview_set = QtWidgets.QWidget(self.GraphPage)
        self.Webview_set.setGeometry(QtCore.QRect(350, 0, 1411, 791))
        self.Webview_set.setStyleSheet("background-color: #D2D7DF;")
        self.Webview_set.setObjectName("Webview_set")
#------------------------------------------------------------------------- WebEngine_SET
        self.WebEngine_set = QtWebEngineWidgets.QWebEngineView(self.Webview_set)
        self.WebEngine_set.setGeometry(QtCore.QRect(0, 0, 1411, 791))
        self.WebEngine_set.setMaximumSize(QtCore.QSize(1411, 16777215))
        self.WebEngine_set.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.WebEngine_set.setObjectName("WebEngine_set")
        self.WebEngine_set.load(QtCore.QUrl("https://www.google.com/"))

        self.Webview_nasdaq = QtWidgets.QWidget(self.GraphPage)
        self.Webview_nasdaq.setGeometry(QtCore.QRect(350, 0, 1411, 791))
        self.Webview_nasdaq.setStyleSheet("background-color: #D2D7DF;")
        self.Webview_nasdaq.setObjectName("Webview_nasdaq")
#------------------------------------------------------------------------- WebEngine_NASDAQ
        self.WebEngine_nasdaq = QtWebEngineWidgets.QWebEngineView(self.Webview_nasdaq)
        self.WebEngine_nasdaq.setGeometry(QtCore.QRect(0, 0, 1411, 791))
        self.WebEngine_nasdaq.setMaximumSize(QtCore.QSize(1411, 16777215))
        self.WebEngine_nasdaq.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.WebEngine_nasdaq.setObjectName("WebEngine_nasdaq")
        self.WebEngine_nasdaq.load(QtCore.QUrl("https://www.youtube.com/"))

        self.Webview_crypto = QtWidgets.QWidget(self.GraphPage)
        self.Webview_crypto.setGeometry(QtCore.QRect(350, 0, 1411, 791))
        self.Webview_crypto.setStyleSheet("background-color: #D2D7DF;")
        self.Webview_crypto.setObjectName("Webview_crypto")
#------------------------------------------------------------------------- WebEngine_Crypto
        self.WebEngine_crypto = QtWebEngineWidgets.QWebEngineView(self.Webview_crypto)
        self.WebEngine_crypto.setGeometry(QtCore.QRect(0, 0, 1411, 791))
        self.WebEngine_crypto.setMaximumSize(QtCore.QSize(1411, 16777215))
        self.WebEngine_crypto.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.WebEngine_crypto.setObjectName("WebEngine_crypto")
        self.WebEngine_crypto.load(QtCore.QUrl("https://www.facebook.com/"))

        self.Graph_select.raise_()
        self.Webview_nasdaq.raise_()
        self.Webview_crypto.raise_()
        self.Webview_set.raise_()
        self.FinancialPage = QtWidgets.QWidget(self.All)
        self.FinancialPage.setGeometry(QtCore.QRect(30, 80, 1761, 791))
        self.FinancialPage.setStyleSheet("background-color: #353535;")
        self.FinancialPage.setObjectName("FinancialPage")
        self.Financial_select = QtWidgets.QWidget(self.FinancialPage)
        self.Financial_select.setGeometry(QtCore.QRect(0, 0, 321, 791))
        self.Financial_select.setStyleSheet("background-color: #E9EBEF;")
        self.Financial_select.setObjectName("Financial_select")
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.Financial_select)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(10, 20, 301, 180))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.pushButton_fncset = QtWidgets.QPushButton(self.verticalLayoutWidget_3)
        self.pushButton_fncset.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pushButton_fncset.setFont(font)
        self.pushButton_fncset.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_fncset.setStyleSheet("background-color: #D2D7DF;")
        self.pushButton_fncset.setObjectName("pushButton_fncset")
        self.verticalLayout_3.addWidget(self.pushButton_fncset)
        self.pushButton_fncnasdaq = QtWidgets.QPushButton(self.verticalLayoutWidget_3)
        self.pushButton_fncnasdaq.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pushButton_fncnasdaq.setFont(font)
        self.pushButton_fncnasdaq.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_fncnasdaq.setStyleSheet("background-color: #D2D7DF;")
        self.pushButton_fncnasdaq.setObjectName("pushButton_fncnasdaq")
        self.verticalLayout_3.addWidget(self.pushButton_fncnasdaq)
        self.financeset = QtWidgets.QWidget(self.FinancialPage)
        self.financeset.setGeometry(QtCore.QRect(350, 0, 1411, 791))
        self.financeset.setStyleSheet("background-color: #D2D7DF;")
        self.financeset.setObjectName("financeset")
        self.comboBox_fncset = QtWidgets.QComboBox(self.financeset)
        self.comboBox_fncset.setGeometry(QtCore.QRect(0, 520, 1241, 31))
        self.comboBox_fncset.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.comboBox_fncset.setStyleSheet("background-color:#ffffff;")
        self.comboBox_fncset.setObjectName("comboBox_fncset")
#----------------------------------------------------------------- Combobox Search Fnc Set
        self.comboBox_fncset.setEditable(True)
        self.comboBox_fncset.setInsertPolicy(QtWidgets.QComboBox.NoInsert)
        self.comboBox_fncset.completer().setCompletionMode(QtWidgets.QCompleter.PopupCompletion)

        self.tableWidget_fncset = QtWidgets.QTableWidget(self.financeset)
        self.tableWidget_fncset.setGeometry(QtCore.QRect(0, 0, 1411, 501))
        self.tableWidget_fncset.setMaximumSize(QtCore.QSize(1411, 16777215))
        self.tableWidget_fncset.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.tableWidget_fncset.setObjectName("tableWidget_fncset")
        self.tableWidget_fncset.setColumnCount(9)
        self.tableWidget_fncset.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_fncset.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_fncset.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_fncset.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_fncset.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_fncset.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_fncset.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_fncset.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_fncset.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_fncset.setHorizontalHeaderItem(8, item)
        self.tableWidget_fncset.horizontalHeader().setDefaultSectionSize(156)
        self.pushButton_updatefncset = QtWidgets.QPushButton(self.financeset)
        self.pushButton_updatefncset.setGeometry(QtCore.QRect(1260, 520, 141, 31))
        self.pushButton_updatefncset.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_updatefncset.setStyleSheet("background-color: rgb(225, 255, 228);")
        self.pushButton_updatefncset.setObjectName("pushButton_updatefncset")
        self.tableWidget_searchfncset = QtWidgets.QTableWidget(self.financeset)
        self.tableWidget_searchfncset.setGeometry(QtCore.QRect(0, 570, 1411, 221))
        self.tableWidget_searchfncset.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.tableWidget_searchfncset.setObjectName("tableWidget_searchfncset")
        self.tableWidget_searchfncset.setColumnCount(9)
        self.tableWidget_searchfncset.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_searchfncset.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_searchfncset.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_searchfncset.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_searchfncset.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_searchfncset.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_searchfncset.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_searchfncset.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_searchfncset.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_searchfncset.setHorizontalHeaderItem(8, item)
        self.tableWidget_searchfncset.horizontalHeader().setDefaultSectionSize(156)
        self.tableWidget_fncset.raise_()
        self.comboBox_fncset.raise_()
        self.pushButton_updatefncset.raise_()
        self.tableWidget_searchfncset.raise_()
        self.financenasdaq = QtWidgets.QWidget(self.FinancialPage)
        self.financenasdaq.setGeometry(QtCore.QRect(350, 0, 1411, 791))
        self.financenasdaq.setStyleSheet("background-color: #D2D7DF;")
        self.financenasdaq.setObjectName("financenasdaq")
        self.comboBox_fncnasdaq = QtWidgets.QComboBox(self.financenasdaq)
        self.comboBox_fncnasdaq.setGeometry(QtCore.QRect(0, 520, 1241, 31))
        self.comboBox_fncnasdaq.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.comboBox_fncnasdaq.setStyleSheet("background-color:#ffffff;")
        self.comboBox_fncnasdaq.setObjectName("comboBox_fncnasdaq")
#----------------------------------------------------------------- Combobox Search Fnc Nasdaq
        self.comboBox_fncnasdaq.setEditable(True)
        self.comboBox_fncnasdaq.setInsertPolicy(QtWidgets.QComboBox.NoInsert)
        self.comboBox_fncnasdaq.completer().setCompletionMode(QtWidgets.QCompleter.PopupCompletion)
        
        self.tableWidget_fncnasdaq = QtWidgets.QTableWidget(self.financenasdaq)
        self.tableWidget_fncnasdaq.setGeometry(QtCore.QRect(0, 0, 1411, 501))
        self.tableWidget_fncnasdaq.setMaximumSize(QtCore.QSize(1411, 16777215))
        self.tableWidget_fncnasdaq.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.tableWidget_fncnasdaq.setObjectName("tableWidget_fncnasdaq")
        self.tableWidget_fncnasdaq.setColumnCount(9)
        self.tableWidget_fncnasdaq.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_fncnasdaq.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_fncnasdaq.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_fncnasdaq.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_fncnasdaq.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_fncnasdaq.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_fncnasdaq.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_fncnasdaq.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_fncnasdaq.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_fncnasdaq.setHorizontalHeaderItem(8, item)
        self.tableWidget_fncnasdaq.horizontalHeader().setDefaultSectionSize(156)
        self.pushButton_updatefncnasdaq = QtWidgets.QPushButton(self.financenasdaq)
        self.pushButton_updatefncnasdaq.setGeometry(QtCore.QRect(1260, 520, 141, 31))
        self.pushButton_updatefncnasdaq.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_updatefncnasdaq.setStyleSheet("background-color: rgb(225, 255, 228);")
        self.pushButton_updatefncnasdaq.setObjectName("pushButton_updatefncnasdaq")
        self.tableWidget_searchfncnasdaq = QtWidgets.QTableWidget(self.financenasdaq)
        self.tableWidget_searchfncnasdaq.setGeometry(QtCore.QRect(0, 570, 1411, 221))
        self.tableWidget_searchfncnasdaq.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.tableWidget_searchfncnasdaq.setObjectName("tableWidget_searchfncnasdaq")
        self.tableWidget_searchfncnasdaq.setColumnCount(9)
        self.tableWidget_searchfncnasdaq.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_searchfncnasdaq.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_searchfncnasdaq.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_searchfncnasdaq.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_searchfncnasdaq.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_searchfncnasdaq.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_searchfncnasdaq.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_searchfncnasdaq.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_searchfncnasdaq.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_searchfncnasdaq.setHorizontalHeaderItem(8, item)
        self.tableWidget_searchfncnasdaq.horizontalHeader().setDefaultSectionSize(156)
        self.Financial_select.raise_()
        self.financenasdaq.raise_()
        self.financeset.raise_()
        self.NewsPage = QtWidgets.QWidget(self.All)
        self.NewsPage.setGeometry(QtCore.QRect(30, 80, 1761, 791))
        self.NewsPage.setStyleSheet("background-color: #353535;")
        self.NewsPage.setObjectName("NewsPage")
        self.News_select = QtWidgets.QWidget(self.NewsPage)
        self.News_select.setGeometry(QtCore.QRect(0, 0, 321, 791))
        self.News_select.setStyleSheet("background-color: #E9EBEF;")
        self.News_select.setObjectName("News_select")
        self.verticalLayoutWidget_4 = QtWidgets.QWidget(self.News_select)
        self.verticalLayoutWidget_4.setGeometry(QtCore.QRect(10, 20, 301, 180))
        self.verticalLayoutWidget_4.setObjectName("verticalLayoutWidget_4")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_4)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.pushButton_newsset = QtWidgets.QPushButton(self.verticalLayoutWidget_4)
        self.pushButton_newsset.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pushButton_newsset.setFont(font)
        self.pushButton_newsset.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_newsset.setStyleSheet("background-color: #D2D7DF;")
        self.pushButton_newsset.setObjectName("pushButton_newsset")
        self.verticalLayout_4.addWidget(self.pushButton_newsset)
        self.pushButton_newsnasdaq = QtWidgets.QPushButton(self.verticalLayoutWidget_4)
        self.pushButton_newsnasdaq.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pushButton_newsnasdaq.setFont(font)
        self.pushButton_newsnasdaq.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_newsnasdaq.setStyleSheet("background-color: #D2D7DF;")
        self.pushButton_newsnasdaq.setObjectName("pushButton_newsnasdaq")
        self.verticalLayout_4.addWidget(self.pushButton_newsnasdaq)
        self.pushButton_newscrypto = QtWidgets.QPushButton(self.verticalLayoutWidget_4)
        self.pushButton_newscrypto.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pushButton_newscrypto.setFont(font)
        self.pushButton_newscrypto.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_newscrypto.setStyleSheet("background-color: #D2D7DF;")
        self.pushButton_newscrypto.setObjectName("pushButton_newscrypto")
        self.verticalLayout_4.addWidget(self.pushButton_newscrypto)
        self.NewsSet = QtWidgets.QWidget(self.NewsPage)
        self.NewsSet.setGeometry(QtCore.QRect(350, 0, 1411, 791))
        self.NewsSet.setStyleSheet("background-color: #D2D7DF;")
        self.NewsSet.setObjectName("NewsSet")
        self.tableWidget_newsset = QtWidgets.QTableWidget(self.NewsSet)
        self.tableWidget_newsset.setGeometry(QtCore.QRect(0, 70, 1411, 721))
        self.tableWidget_newsset.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.tableWidget_newsset.setObjectName("tableWidget_newsset")
        self.tableWidget_newsset.setColumnCount(5)
        self.tableWidget_newsset.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_newsset.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_newsset.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_newsset.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_newsset.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_newsset.setHorizontalHeaderItem(4, item)
        self.comboBox_newsset = QtWidgets.QComboBox(self.NewsSet)
        self.comboBox_newsset.setGeometry(QtCore.QRect(0, 20, 1241, 31))
        self.comboBox_newsset.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.comboBox_newsset.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.comboBox_newsset.setObjectName("comboBox_newsset")
#----------------------------------------------------------------- Combobox Search News Set
        self.comboBox_newsset.setEditable(True)
        self.comboBox_newsset.setInsertPolicy(QtWidgets.QComboBox.NoInsert)
        self.comboBox_newsset.completer().setCompletionMode(QtWidgets.QCompleter.PopupCompletion)

        self.pushButton_updatenewsset = QtWidgets.QPushButton(self.NewsSet)
        self.pushButton_updatenewsset.setGeometry(QtCore.QRect(1260, 20, 141, 31))
        self.pushButton_updatenewsset.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_updatenewsset.setStyleSheet("background-color: rgb(225, 255, 228);")
        self.pushButton_updatenewsset.setObjectName("pushButton_updatenewsset")
        self.NewsNasdaq = QtWidgets.QWidget(self.NewsPage)
        self.NewsNasdaq.setGeometry(QtCore.QRect(350, 0, 1411, 791))
        self.NewsNasdaq.setStyleSheet("background-color: #D2D7DF;")
        self.NewsNasdaq.setObjectName("NewsNasdaq")
        self.tableWidget_newsnasdaq = QtWidgets.QTableWidget(self.NewsNasdaq)
        self.tableWidget_newsnasdaq.setGeometry(QtCore.QRect(0, 70, 1411, 721))
        self.tableWidget_newsnasdaq.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.tableWidget_newsnasdaq.setObjectName("tableWidget_newsnasdaq")
        self.tableWidget_newsnasdaq.setColumnCount(5)
        self.tableWidget_newsnasdaq.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_newsnasdaq.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_newsnasdaq.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_newsnasdaq.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_newsnasdaq.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_newsnasdaq.setHorizontalHeaderItem(4, item)
        self.comboBox_newsnasdaq = QtWidgets.QComboBox(self.NewsNasdaq)
        self.comboBox_newsnasdaq.setGeometry(QtCore.QRect(0, 20, 1241, 31))
        self.comboBox_newsnasdaq.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.comboBox_newsnasdaq.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.comboBox_newsnasdaq.setObjectName("comboBox_newsnasdaq")
#----------------------------------------------------------------- Combobox Search News Nasdaq
        self.comboBox_newsnasdaq.setEditable(True)
        self.comboBox_newsnasdaq.setInsertPolicy(QtWidgets.QComboBox.NoInsert)
        self.comboBox_newsnasdaq.completer().setCompletionMode(QtWidgets.QCompleter.PopupCompletion)

        self.pushButton_updatenewsnasdaq = QtWidgets.QPushButton(self.NewsNasdaq)
        self.pushButton_updatenewsnasdaq.setGeometry(QtCore.QRect(1260, 20, 141, 31))
        self.pushButton_updatenewsnasdaq.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_updatenewsnasdaq.setStyleSheet("background-color: rgb(225, 255, 228);")
        self.pushButton_updatenewsnasdaq.setObjectName("pushButton_updatenewsnasdaq")
        self.NewsCrypto = QtWidgets.QWidget(self.NewsPage)
        self.NewsCrypto.setGeometry(QtCore.QRect(350, 0, 1411, 791))
        self.NewsCrypto.setStyleSheet("background-color: #D2D7DF;")
        self.NewsCrypto.setObjectName("NewsCrypto")
        self.tableWidget_newscrypto = QtWidgets.QTableWidget(self.NewsCrypto)
        self.tableWidget_newscrypto.setGeometry(QtCore.QRect(0, 70, 1411, 721))
        self.tableWidget_newscrypto.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.tableWidget_newscrypto.setObjectName("tableWidget_newscrypto")
        self.tableWidget_newscrypto.setColumnCount(5)
        self.tableWidget_newscrypto.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_newscrypto.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_newscrypto.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_newscrypto.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_newscrypto.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_newscrypto.setHorizontalHeaderItem(4, item)
        self.comboBox_newscrypto = QtWidgets.QComboBox(self.NewsCrypto)
        self.comboBox_newscrypto.setGeometry(QtCore.QRect(0, 20, 1241, 31))
        self.comboBox_newscrypto.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.comboBox_newscrypto.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.comboBox_newscrypto.setObjectName("comboBox_newscrypto")
#----------------------------------------------------------------- Combobox Search News Crypto
        self.comboBox_newscrypto.setEditable(True)
        self.comboBox_newscrypto.setInsertPolicy(QtWidgets.QComboBox.NoInsert)
        self.comboBox_newscrypto.completer().setCompletionMode(QtWidgets.QCompleter.PopupCompletion)

        self.pushButton_updatenewscrypto = QtWidgets.QPushButton(self.NewsCrypto)
        self.pushButton_updatenewscrypto.setGeometry(QtCore.QRect(1260, 20, 141, 31))
        self.pushButton_updatenewscrypto.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_updatenewscrypto.setStyleSheet("background-color: rgb(225, 255, 228);")
        self.pushButton_updatenewscrypto.setObjectName("pushButton_updatenewscrypto")
        self.News_select.raise_()
        self.NewsCrypto.raise_()
        self.NewsNasdaq.raise_()
        self.NewsSet.raise_()
        self.Header.raise_()
        self.FinancialPage.raise_()
        self.NewsPage.raise_()
        self.GraphPage.raise_()
        self.DataPage.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1820, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.pushButton_dataset.clicked.connect(self.tableset.show) # type: ignore
        self.pushButton_datanasdaq.clicked.connect(self.tableset.hide) # type: ignore
        self.pushButton_datacrypto.clicked.connect(self.tableset.hide) # type: ignore
        self.pushButton_dataset.clicked.connect(self.tablenasdaq.hide) # type: ignore
        self.pushButton_datanasdaq.clicked.connect(self.tablenasdaq.show) # type: ignore
        self.pushButton_datacrypto.clicked.connect(self.tablenasdaq.hide) # type: ignore
        self.pushButton_dataset.clicked.connect(self.tablecrypto.hide) # type: ignore
        self.pushButton_datanasdaq.clicked.connect(self.tablecrypto.hide) # type: ignore
        self.pushButton_datacrypto.clicked.connect(self.tablecrypto.show) # type: ignore
        self.pushButton_graph.clicked.connect(self.DataPage.hide) # type: ignore
        self.pushButton_data.clicked.connect(self.DataPage.show) # type: ignore
        self.pushButton_financial.clicked.connect(self.DataPage.hide) # type: ignore
        self.pushButton_news.clicked.connect(self.DataPage.hide) # type: ignore
        self.pushButton_data.clicked.connect(self.GraphPage.hide) # type: ignore
        self.pushButton_graph.clicked.connect(self.GraphPage.show) # type: ignore
        self.pushButton_financial.clicked.connect(self.GraphPage.hide) # type: ignore
        self.pushButton_news.clicked.connect(self.GraphPage.hide) # type: ignore
        self.pushButton_news.clicked.connect(self.NewsPage.show) # type: ignore
        self.pushButton_financial.clicked.connect(self.NewsPage.hide) # type: ignore
        self.pushButton_graph.clicked.connect(self.NewsPage.hide) # type: ignore
        self.pushButton_data.clicked.connect(self.NewsPage.hide) # type: ignore
        self.pushButton_data.clicked.connect(self.FinancialPage.hide) # type: ignore
        self.pushButton_graph.clicked.connect(self.FinancialPage.hide) # type: ignore
        self.pushButton_financial.clicked.connect(self.FinancialPage.show) # type: ignore
        self.pushButton_news.clicked.connect(self.FinancialPage.hide) # type: ignore
        self.pushButton_fncset.clicked.connect(self.financeset.show) # type: ignore
        self.pushButton_fncnasdaq.clicked.connect(self.financeset.hide) # type: ignore
        self.pushButton_fncset.clicked.connect(self.financenasdaq.hide) # type: ignore
        self.pushButton_fncnasdaq.clicked.connect(self.financenasdaq.show) # type: ignore
        self.pushButton_newsset.clicked.connect(self.NewsSet.show) # type: ignore
        self.pushButton_newsnasdaq.clicked.connect(self.NewsSet.hide) # type: ignore
        self.pushButton_newscrypto.clicked.connect(self.NewsSet.hide) # type: ignore
        self.pushButton_newsset.clicked.connect(self.NewsNasdaq.hide) # type: ignore
        self.pushButton_newsnasdaq.clicked.connect(self.NewsNasdaq.show) # type: ignore
        self.pushButton_newscrypto.clicked.connect(self.NewsNasdaq.hide) # type: ignore
        self.pushButton_newsset.clicked.connect(self.NewsCrypto.hide) # type: ignore
        self.pushButton_newsnasdaq.clicked.connect(self.NewsCrypto.hide) # type: ignore
        self.pushButton_newscrypto.clicked.connect(self.NewsCrypto.show) # type: ignore
        self.pushButton_graphset.clicked.connect(self.Webview_set.show) # type: ignore
        self.pushButton_graphnasdaq.clicked.connect(self.Webview_set.hide) # type: ignore
        self.pushButton_graphcrypto.clicked.connect(self.Webview_set.hide) # type: ignore
        self.pushButton_graphset.clicked.connect(self.Webview_nasdaq.hide) # type: ignore
        self.pushButton_graphnasdaq.clicked.connect(self.Webview_nasdaq.show) # type: ignore
        self.pushButton_graphcrypto.clicked.connect(self.Webview_nasdaq.hide) # type: ignore
        self.pushButton_graphset.clicked.connect(self.Webview_crypto.hide) # type: ignore
        self.pushButton_graphnasdaq.clicked.connect(self.Webview_crypto.hide) # type: ignore
        self.pushButton_graphcrypto.clicked.connect(self.Webview_crypto.show) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_data.setText(_translate("MainWindow", "Data"))
        self.pushButton_graph.setText(_translate("MainWindow", "Graph"))
        self.pushButton_financial.setText(_translate("MainWindow", "Financial"))
        self.pushButton_news.setText(_translate("MainWindow", "News"))
        self.pushButton_dataset.setText(_translate("MainWindow", "SET"))
        self.pushButton_datanasdaq.setText(_translate("MainWindow", "NASDAQ"))
        self.pushButton_datacrypto.setText(_translate("MainWindow", "CRYPTO"))
        item = self.tableWidget_datanasdaq.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Symbol"))
        item = self.tableWidget_datanasdaq.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Name"))
        item = self.tableWidget_datanasdaq.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Market"))
        item = self.tableWidget_datanasdaq.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Sector"))
        item = self.tableWidget_searchnasdaq.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Symbol"))
        item = self.tableWidget_searchnasdaq.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Name"))
        item = self.tableWidget_searchnasdaq.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Market"))
        item = self.tableWidget_searchnasdaq.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Sector"))
        item = self.tableWidget_searchnasdaq.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Description"))
        self.pushButton_updatenasdaq.setText(_translate("MainWindow", "Update"))
        item = self.tableWidget_dataset.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Symbol"))
        item = self.tableWidget_dataset.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Name"))
        item = self.tableWidget_dataset.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Market"))
        item = self.tableWidget_dataset.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Sector"))
        item = self.tableWidget_dataset.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Description"))
#------------------------------------------------------------------ Column Width Dataset
        self.tableWidget_dataset.setColumnWidth(1, 250)
        self.tableWidget_dataset.setColumnWidth(4, 700)

        item = self.tableWidget_searchset.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Symbol"))
        item = self.tableWidget_searchset.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Name"))
        item = self.tableWidget_searchset.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Market"))
        item = self.tableWidget_searchset.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Sector"))
        item = self.tableWidget_searchset.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Destination"))
#------------------------------------------------------------------ Column Width Datasearch set
        self.tableWidget_searchset.setColumnWidth(1, 250)
        self.tableWidget_searchset.setColumnWidth(4, 700)

        self.pushButton_updateset.setText(_translate("MainWindow", "Update"))
        item = self.tableWidget_datacrypto.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Symbol"))
        item = self.tableWidget_datacrypto.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Name"))
        item = self.tableWidget_searchcrypto.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Symbol"))
        item = self.tableWidget_searchcrypto.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Name"))
        self.pushButton_updatecrypto.setText(_translate("MainWindow", "Update"))
        self.pushButton_graphset.setText(_translate("MainWindow", "SET"))
        self.pushButton_graphnasdaq.setText(_translate("MainWindow", "NASDAQ"))
        self.pushButton_graphcrypto.setText(_translate("MainWindow", "CRYPTO"))
        self.pushButton_fncset.setText(_translate("MainWindow", "SET"))
        self.pushButton_fncnasdaq.setText(_translate("MainWindow", "NASDAQ"))
        item = self.tableWidget_fncset.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Asset"))
        item = self.tableWidget_fncset.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "TotalDebt"))
        item = self.tableWidget_fncset.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Equity"))
        item = self.tableWidget_fncset.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Revenue"))
        item = self.tableWidget_fncset.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "NetProfit"))
        item = self.tableWidget_fncset.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "ROA"))
        item = self.tableWidget_fncset.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "ROE"))
        item = self.tableWidget_fncset.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "Period"))
        item = self.tableWidget_fncset.horizontalHeaderItem(8)
        item.setText(_translate("MainWindow", "Symbol"))
        self.pushButton_updatefncset.setText(_translate("MainWindow", "Update"))
        item = self.tableWidget_searchfncset.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Asset"))
        item = self.tableWidget_searchfncset.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "TotalDebt"))
        item = self.tableWidget_searchfncset.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Equity"))
        item = self.tableWidget_searchfncset.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Revenue"))
        item = self.tableWidget_searchfncset.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "NetProfit"))
        item = self.tableWidget_searchfncset.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "ROA"))
        item = self.tableWidget_searchfncset.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "ROE"))
        item = self.tableWidget_searchfncset.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "Period"))
        item = self.tableWidget_searchfncset.horizontalHeaderItem(8)
        item.setText(_translate("MainWindow", "Symbol"))
        item = self.tableWidget_fncnasdaq.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Asset"))
        item = self.tableWidget_fncnasdaq.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "TotalDebt"))
        item = self.tableWidget_fncnasdaq.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Equity"))
        item = self.tableWidget_fncnasdaq.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Revenue"))
        item = self.tableWidget_fncnasdaq.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "NetProfit"))
        item = self.tableWidget_fncnasdaq.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "ROA"))
        item = self.tableWidget_fncnasdaq.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "ROE"))
        item = self.tableWidget_fncnasdaq.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "Period"))
        item = self.tableWidget_fncnasdaq.horizontalHeaderItem(8)
        item.setText(_translate("MainWindow", "Symbol"))
        self.pushButton_updatefncnasdaq.setText(_translate("MainWindow", "Update"))
        item = self.tableWidget_searchfncnasdaq.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Asset"))
        item = self.tableWidget_searchfncnasdaq.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "TotalDebt"))
        item = self.tableWidget_searchfncnasdaq.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Equity"))
        item = self.tableWidget_searchfncnasdaq.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Revenue"))
        item = self.tableWidget_searchfncnasdaq.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "NetProfit"))
        item = self.tableWidget_searchfncnasdaq.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "ROA"))
        item = self.tableWidget_searchfncnasdaq.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "ROE"))
        item = self.tableWidget_searchfncnasdaq.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "Period"))
        item = self.tableWidget_searchfncnasdaq.horizontalHeaderItem(8)
        item.setText(_translate("MainWindow", "Symbol"))
        self.pushButton_newsset.setText(_translate("MainWindow", "SET"))
        self.pushButton_newsnasdaq.setText(_translate("MainWindow", "NASDAQ"))
        self.pushButton_newscrypto.setText(_translate("MainWindow", "CRYPTO"))
        item = self.tableWidget_newsset.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Date"))
        item = self.tableWidget_newsset.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Title"))
        item = self.tableWidget_newsset.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Description"))
        item = self.tableWidget_newsset.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Link"))
        item = self.tableWidget_newsset.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Source"))
#------------------------------------------------------------------ Column Width News Set
        self.tableWidget_newsset.setColumnWidth(0, 150)
        self.tableWidget_newsset.setColumnWidth(1, 500)
        self.tableWidget_newsset.setColumnWidth(2, 500)
        self.tableWidget_newsset.setColumnWidth(3, 200)
        self.tableWidget_newsset.setColumnWidth(4, 200)

        self.pushButton_updatenewsset.setText(_translate("MainWindow", "Update"))
        item = self.tableWidget_newsnasdaq.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Date"))
        item = self.tableWidget_newsnasdaq.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Title"))
        item = self.tableWidget_newsnasdaq.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Description"))
        item = self.tableWidget_newsnasdaq.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Link"))
        item = self.tableWidget_newsnasdaq.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Source"))
#------------------------------------------------------------------ Column Width News Nasdaq
        self.tableWidget_newsnasdaq.setColumnWidth(0, 150)
        self.tableWidget_newsnasdaq.setColumnWidth(1, 500)
        self.tableWidget_newsnasdaq.setColumnWidth(2, 500)
        self.tableWidget_newsnasdaq.setColumnWidth(3, 200)
        self.tableWidget_newsnasdaq.setColumnWidth(4, 200)

        self.pushButton_updatenewsnasdaq.setText(_translate("MainWindow", "Update"))
        item = self.tableWidget_newscrypto.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Date"))
        item = self.tableWidget_newscrypto.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Title"))
        item = self.tableWidget_newscrypto.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Description"))
        item = self.tableWidget_newscrypto.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Link"))
        item = self.tableWidget_newscrypto.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Source"))
#------------------------------------------------------------------ Column Width News Crypto
        self.tableWidget_newscrypto.setColumnWidth(0, 150)
        self.tableWidget_newscrypto.setColumnWidth(1, 500)
        self.tableWidget_newscrypto.setColumnWidth(2, 500)
        self.tableWidget_newscrypto.setColumnWidth(3, 200)
        self.tableWidget_newscrypto.setColumnWidth(4, 200)

        self.pushButton_updatenewscrypto.setText(_translate("MainWindow", "Update"))

#------------------------------------------------------ Name of Stock and Crypto
def combobox_SET():
    conn = sqlite3.connect('share_V3.sqlite')
    cursor = conn.cursor()
    cursor.execute("""SELECT Symbol FROM Information WHERE MarketId = 1 ORDER BY Symbol ASC""")
    result = cursor.fetchall()
    values = [item[0] for item in result]
    return values
def combobox_NASDAQ():
    conn = sqlite3.connect('share_V3.sqlite')
    cursor = conn.cursor()
    cursor.execute("""SELECT Symbol FROM Information WHERE MarketId = 2 ORDER BY Symbol ASC""")
    result = cursor.fetchall()
    values = [item[0] for item in result]
    return values
def combobox_CRYPTO():
    conn = sqlite3.connect('share_V3.sqlite')
    cursor = conn.cursor()
    cursor.execute("""SELECT Symbol FROM Information WHERE MarketId = 3 ORDER BY Symbol ASC""")
    result = cursor.fetchall()
    values = [item[0] for item in result]
    return values

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
#------------------------------------------------------- Set Value Combobox
    ui.comboBox_dataset.addItems(combobox_SET())
    ui.comboBox_fncset.addItems(combobox_SET())
    ui.comboBox_newsset.addItems(combobox_SET())
    ui.comboBox_datanasdaq.addItems(combobox_NASDAQ())
    ui.comboBox_fncnasdaq.addItems(combobox_NASDAQ())
    ui.comboBox_newsnasdaq.addItems(combobox_NASDAQ())
    ui.comboBox_datacrypto.addItems(combobox_CRYPTO())
    ui.comboBox_newscrypto.addItems(combobox_CRYPTO())

    MainWindow.show()
    sys.exit(app.exec_())
